# Call this workflow like this:
# jobs:
#   bump-version:
#     uses: aricAI/github-actions/.github/workflows/tag.yml
#     with:
#       default_branch: main # optional, default: main
#     secrets:
#       SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }} # required

on:
  workflow_call:
    outputs:
      new_version:
        description: 'The new version'
        value: ${{ jobs.bump-version.outputs.new_version }}
    inputs:
      default_branch:
        description: 'Default branch name'
        default: main
        required: false
        type: string
    secrets:
      SERVICE_TOKEN:
        required: true

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.output_version.outputs.new_version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.default_branch }}
        fetch-depth: 0
        token: ${{ secrets.SERVICE_TOKEN }}
    - name: Compute new version number
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.SERVICE_TOKEN }}
        release_branches: ${{ inputs.default_branch }}
        default_bump: patch
        dry_run: true  # Perform dryrun first to calculate new version
    - name: Get version file name set variables
      run: |
        pkg_name=$(grep -P 'version = \{attr = .*\}' pyproject.toml | grep -oP '\w+.__version__')
        init_file="./src/${pkg_name//.__version__}/__init__.py"
        echo "VERSION_FILE=$init_file" >> "$GITHUB_ENV"
        echo "VERSION=${{ steps.tag_version.outputs.new_version }}" >> "$GITHUB_ENV"
    - name: Update version file with new version
      run: |
        grep "__version__" "$VERSION_FILE"
        sed -i --debug --expression="s|__version__.*|__version__ = \"${{ env.VERSION }}\"|" "$VERSION_FILE"
    - name: Set output
      id: output_version
      run: echo "new_version=${{ env.VERSION }}" >> "$GITHUB_OUTPUT"
    - name: Commit and Push version bump
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "ci: version bump [skip actions]"
        add: ${{ env.VERSION_FILE }}
    - name: Update tag
      run: |
        git tag v${{ env.VERSION }}
        git push origin v${{ env.VERSION }}
